add ngo model #issue3
RCDD-202203-TUR-BEW/backend-capstone-turkey-teach-kids pull request #33
Opened 2022-07-27 09:59 UTC by BerkAkipek

Fixes #3

2022-07-27 13:49 UTC, muslimomar requested changes
Great work

2022-07-27 13:49 UTC, muslimomar commented on src/models/ngo.js
> +module.exports = mongoose.model('ngo', ngoSchema);
let's name the `ngo` model as `Ngo`.

2022-07-27 13:49 UTC, muslimomar commented on src/models/ngo.js
> +  ngoName: {
can you rename it as `name` only.

2022-07-27 13:49 UTC, muslimomar commented on src/models/ngo.js
> +  webSite: {
Let's make it `website`

2022-07-27 13:49 UTC, muslimomar commented on src/models/ngo.js
> +    required: true,
`password` shouldn't be required, because we might use social auth like google auth

2022-07-28 06:12 UTC, BerkAkipek commented
Hello Muslim,
I edit model in from your comments.

2022-07-28 10:00 UTC, merged