Abdulhafiz96/implement post signup & signin
RCDD-202203-TUR-BEW/backend-capstone-turkey-teach-kids pull request #38
Opened 2022-08-02 12:49 UTC by abdulhafiz96

2022-08-02 13:06 UTC, dilarafirtina approved these changes

2022-08-02 13:34 UTC, dilarafirtina approved these changes

2022-08-04 15:30 UTC, muslimomar requested changes
The efforts you've put into this issue are commendable and truly appreciated. I'm glad I have you on my team 👏💪

2022-08-04 15:30 UTC, muslimomar commented on src/controllers/auth.js
> +    { email: user.email, username: user.username },
For the payload, let's store `user._id` only.

```javascript
       { _id: user._id.toHexString() };
```

2022-08-04 15:30 UTC, muslimomar commented on src/controllers/auth.js
> +      expiresIn: '14h',
make the expiration 14 days

2022-08-04 15:30 UTC, muslimomar commented on src/controllers/auth.js
> +    expires: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
make the expiration 14 days

2022-08-04 15:30 UTC, muslimomar commented on src/middlewares/auth.js
> +      req.user = jwt.verify(token, process.env.JWT_SECRET);
surround the `jwt.verify` with a `try/catch`, and in `catch` block, send a message to the user, about an invalid/expired token.
something like this: 

```javascript
       try {
        req.user = jwt.verify(token, process.env.JWT_SECRET);
      } catch (err) {
        return next(new ErrorResponse('Invalid/expired token', 401));
      }
```

2022-08-04 15:30 UTC, muslimomar commented on src/middlewares/express-validator-err.js
> +};
amazing job utilizing a validator middleware 💪

2022-08-04 15:30 UTC, muslimomar commented on src/middlewares/express-validator-err.js
> +
let's give this file another name, like `bodyValidator.js`

2022-08-04 15:30 UTC, muslimomar commented on src/middlewares/validatorSchemas.js
> +    .withMessage('passwords do not match'),
`password2` could be removed.

2022-08-04 15:30 UTC, muslimomar commented on src/routes/auth.js
> +router.post('/login', validateSignin, validate, authController.login);
Splendid work again 👏

2022-08-04 17:00 UTC, abdulhafiz96 commented
thank you so much for the amazing feedback, I have fixed all the issues you mentioned

2022-08-04 17:04 UTC, muslimomar approved these changes
Outstanding work! 🔥

2022-08-04 17:04 UTC, merged