Implement POST /events
RCDD-202203-TUR-BEW/backend-capstone-turkey-teach-kids pull request #49
Opened 2022-08-05 11:53 UTC by dilarafirtina

2022-08-10 10:24 UTC, yamanrajab90 commented on src/controllers/__tests__/events.test.js
>      lastName: 'Fırtına',
test passed successfully, the Last name includes  The character U+0131 "ı" could be confused with the character U+0069 "i", which is more common in source code

2022-08-10 10:26 UTC, yamanrajab90 commented on src/controllers/__tests__/events.test.js
> +        done();
Awesome work! 
excellent testing strategy.

2022-08-10 10:32 UTC, yamanrajab90 commented on src/routes/events.js
> +const { isAuth } = require('../middlewares/auth');
good declaration in accordance with eslint.
Great job/

2022-08-10 10:32 UTC, yamanrajab90 approved these changes

2022-08-15 00:46 UTC, muslimomar requested changes

2022-08-15 00:46 UTC, muslimomar commented on src/controllers/events.js
> +    newEvent.declinedApplicants.push(req.body.declinedApplicantsId);
The event should have empty `pendingApplicants, approved, declined`, so just leave them as their default values.

2022-08-15 00:46 UTC, muslimomar commented on src/controllers/events.js
> +  newEvent.topic = req.body.topic;
You could use a shorthand for these operations: 

`const newEvent = new Event(req.body);` or `const newEvent = await Event.create(req.body)`

2022-08-15 00:46 UTC, muslimomar commented on src/controllers/__tests__/events.test.js
> +  id: '1',
Why are you removing the underscore? 🤔

2022-08-15 00:46 UTC, muslimomar commented on src/controllers/__tests__/events.test.js
> +        message: 'You are not authorized to delete this event',
The message says: 'You are not authorized to delete this event'. delete or add an event? 🤣

2022-08-16 10:17 UTC, closed without merging