Abdulhafiz96/18 implement get profile
RCDD-202203-TUR-BEW/backend-capstone-turkey-teach-kids pull request #50
Opened 2022-08-05 12:12 UTC by abdulhafiz96

implemented GET, PATCH /profile

2022-08-05 14:03 UTC, muslimomar requested changes
Splendid work! 👏 don't forget to apply validation took 👌

2022-08-05 14:03 UTC, muslimomar commented on src/controllers/profile.js
> +        },
Here is an easier way to use the update fields without listing them one by one. 😉

```javascript 
{ $set: req.body }
```
now Mongodb will take all keys from `req.body` and use them to update our document (volunteer/ngo).
Make sure you apply that for Ngo too

2022-08-05 14:03 UTC, muslimomar commented on src/controllers/profile.js
> +      (await Volunteer.findOneAndUpdate(
Before we update, let's make sure that the new email/username (`req.body.email`), are not used by other ngos/volunteers.
just like you checked it at signup

2022-08-06 00:08 UTC, abdulhafiz96 commented
issue 18 has been fixed

2022-08-07 21:48 UTC, muslimomar approved these changes

2022-08-07 21:48 UTC, muslimomar commented on src/controllers/profile.js
> +  const checkMail1 = await Volunteer.find({
since you're querying for a single document/volunteer, it's much ideal to use `findOne`.

2022-08-07 21:48 UTC, muslimomar commented on src/controllers/profile.js
> +  const checkMail2 = await Ngo.find({
use `findOne` again

2022-08-07 21:48 UTC, muslimomar commented on src/middlewares/validatorSchemas.js
> +const validateProfile = [
great work on applying validation 🔥

2022-08-07 21:48 UTC, merged