issue #5 has been fixed
RCDD-202203-TUR-BEW/backend-capstone-turkey-teach-kids pull request #6
Opened 2022-07-23 09:46 UTC by abdulhafiz96

2022-07-23 12:58 UTC, dilarafirtina approved these changes

2022-07-25 17:50 UTC, muslimomar requested changes
Amazing work @abdulhafiz96!

2022-07-25 17:50 UTC, muslimomar commented on src/models/volunteer.js
> +      required: true,
`password` won't be required always, because we might be social network auth too, like google auth.

2022-07-25 17:50 UTC, muslimomar commented on src/models/volunteer.js
> +    },
The naming convention should be `createdAt` and `updatedAt`, so you don't need to override it, let's stick with the default. `timestamps: true`

2022-07-25 19:17 UTC, dilarafirtina approved these changes

2022-07-26 07:56 UTC, abdulhafiz96 commented
the requested changes have been made ✔️

2022-07-26 21:05 UTC, muslimomar approved these changes
Well done!

2022-07-26 21:05 UTC, merged